name: Renew Gratis Service

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 6 * *'

jobs:
  renew_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright browsers
        run: playwright install chromium

      - name: Run the renewal script
        env:
          GRATIS_COOKIE: ${{ secrets.GRATIS_COOKIE }}
          GRATIS_EMAIL: ${{ secrets.GRATIS_EMAIL }}
          GRATIS_PASSWORD: ${{ secrets.GRATIS_PASSWORD }}
        run: python renew_script.py

      # MODIFIED: 上传所有生成的截图作为构建产物
      # 无论成功或失败，都执行此步骤，以便我们能看到调试截图
      - name: Upload screenshots
        if: always() # 无论成功或失败都运行
        uses: actions/upload-artifact@v4
        with:
          name: execution-screenshots
          path: |
            *.png
          if-no-files-found: ignore
